keys:
  - &primary age17wwujedpm5tp69jajujcgj50g9pjfr4vhghufa2lqxc8r5nk8saq269338
creation_rules:
  - path_regex: modules/shared/secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
